name: GCP MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Train ML Model
      run: |
        python train_gcp.py

    - name: Deploy ML Model
      run: |
        python deploy_gcp_model.py

    - name: Run Monitoring
      run: |
        python monitor_gcp.py